Feature/use anchor id from taxonomyfield in dynamicform
pnp/sp-dev-fx-controls-react pull request #1312
Opened 2022-09-14 15:26 UTC by SmarterJB

| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | fixes #1310

#### What's in this Pull Request?
This change allows the dynamic form to use the anchor id which is set in the field settings of the taxonomy field. I also changed the wording of the german localization because the word "Laufzeit" in german means "running time" in english! "Knoten" now refers to the "node" of the termstore which is more suiting in my opinion.

This is both a bugfix (because when I used the dynamic form, I wondered why it isnt working) and a new feature!

2022-09-28 10:28 UTC, joelfmrodrigues commented
@SmarterJB sorry for the delay on this. Can you please review the conflicts?

2022-09-28 10:35 UTC, SmarterJB commented
No problem! I resolved the conflicts!

2022-10-06 08:48 UTC, SmarterJB commented
Hello @joelfmrodrigues can this be included in the next release aswell? Then all my current issues should be fixed!

Cheers!

2022-10-06 09:37 UTC, joelfmrodrigues commented
Sorry, 3.11.0 was just published some minutes ago (should have been 2 days ago but there was an issue publishing it to npm)
I tried to review the PR before the release but just couldn't find the time.

2022-10-06 09:46 UTC, SmarterJB commented
okay no problem! we can work with the beta version once this is through! Thanks for the quick response! :)

2022-11-04 16:05 UTC, AJIXuMuK requested changes

2022-11-04 16:05 UTC, AJIXuMuK commented on src/services/SPTermStorePickerService.ts
> -    this.clientServiceUrl = this.context.pageContext.web.absoluteUrl + '/_vti_bin/client.svc/ProcessQuery';
this change is not needed

2022-11-16 14:05 UTC, merged