Added file handling in DynamicForm
pnp/sp-dev-fx-controls-react pull request #1625
Opened 2023-08-14 13:24 UTC by GuidoZam

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x ]
| New sample?      | [ ]

#### What's in this Pull Request?

Added the possibility to choose the file to be uploaded to the document library.

2023-08-14 14:01 UTC, aaclage commented on src/loc/pt-pt.ts
> +  "DynamicFormChooseFileLabel": "File",
Ficheiro

2023-08-14 14:02 UTC, aaclage commented on src/loc/pt-pt.ts
> +  "DynamicFormChooseFileButtonText": "Select file",
Selecionar ficheiro

2023-08-14 14:02 UTC, aaclage commented on src/loc/pt-pt.ts
> +  "DynamicFormRequiredFileMessage": "File is required.",
Ficheiro é necessário

2023-09-19 20:19 UTC, michaelmaillot commented on src/loc/fr-ca.ts
> +  "DynamicFormChooseFileLabel": "File",
Fichier

2023-09-19 20:20 UTC, michaelmaillot commented on src/loc/fr-ca.ts
> +  "DynamicFormChooseFileButtonText": "Select file",
Sélectionnez un fichier

2023-09-19 20:21 UTC, michaelmaillot commented on src/loc/fr-ca.ts
> +  "DynamicFormRequiredFileMessage": "File is required.",
Un fichier est requis.

2023-09-19 20:21 UTC, michaelmaillot commented on src/loc/fr-fr.ts
> +  "DynamicFormChooseFileLabel": "File",
Fichier

2023-09-19 20:21 UTC, michaelmaillot commented on src/loc/fr-fr.ts
> +  "DynamicFormChooseFileButtonText": "Select file",
Sélectionnez un fichier

2023-09-19 20:22 UTC, michaelmaillot commented on src/loc/fr-fr.ts
> +  "DynamicFormRequiredFileMessage": "File is required.",
Un fichier est requis.

2023-09-19 20:22 UTC, michaelmaillot commented
Hi @GuidoZam,

Thanks for this enhancement!

After going through the code and the new props spec, I want to be sure of what you want to cover.

If I read you PR comment, you want to provide a feature that allows to upload a file to a **document library**.

But if I have a look at the `enableFileSelection` prop definition [here](https://github.com/pnp/sp-dev-fx-controls-react/pull/1625/files#diff-51ca6beb7579356bbb03cd23b2b21ac112ceddeda25e950a9561aae5e8a52954R87), it says that you can add a file to a **list item**.

I tried with both approaches and it seems that it's not working with the list item context.

Here's what I suggest:

* If you want to only cover document libraries, it would be better to clarify it in the prop definition
    * In that case, maybe adding a couple of checks in order to display the file selection button based on the `BaseTemplate` property for example
* If you want to cover also lists, it has to be covered in the code
    * You can adapt the queries to do (add / update list item + add list attachment) from the `BaseTemplate` property also


In all the cases, can you upade the control's documentation page to reflect the enhancement? You could add a screen / video that covers this new feature if you want to 🙂

2023-09-20 06:59 UTC, michaelmaillot commented on src/controls/dynamicForm/DynamicForm.tsx
> +  private addFileToLibrary = async (objects: {}) => {
Please specify the type of the method

2023-09-20 06:59 UTC, michaelmaillot commented on src/controls/dynamicForm/DynamicForm.tsx
> +      onBeforeSubmit,
You can remove unused props

2023-09-26 20:59 UTC, GuidoZam commented
Thanks @michaelmaillot for the reviews and the feedbacks.
I want to cover the case of adding the file when creating a new list item inside a document library, I'll try to enhance the prop description and to also add some checks.

2023-10-08 16:29 UTC, AJIXuMuK commented
@GuidoZam - seems like I still can enable file upload for standard lists (not doc libs)

2023-10-22 08:42 UTC, GuidoZam commented
@AJIXuMuK I've added a check using the contentTypeId property of the dynamicForm control, that should be enough to restrict the usage only to document libraries.

2023-10-26 06:48 UTC, michaelmaillot commented
Hi @GuidoZam, thanks for the update!

I've made some comments as a review.

Sorry to insist but could you please update the DynamicForm's documentation page in order to reflect the new props added in this PR? Feel free to insert screens / gifs or not.

2023-11-14 11:41 UTC, GuidoZam commented
Hi @michaelmaillot  I've made some improvements, can you please check if now it's all good?

2023-11-15 00:31 UTC, michaelmaillot commented
Hi @GuidoZam,

Sounds good to me! Can you just resolve the remaining conflict before I merge your PR please?

2023-11-21 20:58 UTC, GuidoZam commented
Hi @michaelmaillot, I've resolved the remaining conflict.
For the update regarding the doc page I cannot see anything, am I missing something?

2023-11-21 22:16 UTC, michaelmaillot commented
I've mentioned you in the review comment [here](https://github.com/pnp/sp-dev-fx-controls-react/pull/1625/files#diff-abe3c69e4f9c0b785e0f6bd18be58cf87abde6ea714de2e2f637ff069d4adf10R62)

2023-11-24 11:31 UTC, GuidoZam commented
@michaelmaillot sorry but I can't see any comment there, if I click on the link you inserted it just select the row 62 of the DynamicForm.md file.

2023-11-24 14:28 UTC, michaelmaillot requested changes

2023-11-24 14:29 UTC, michaelmaillot commented
> @michaelmaillot sorry but I can't see any comment there, if I click on the link you inserted it just select the row 62 of the DynamicForm.md file.

Nevermind, forgot to submit my review.........🤦‍♂️

Sorry about that.

2023-11-26 09:27 UTC, GuidoZam commented
> > @michaelmaillot sorry but I can't see any comment there, if I click on the link you inserted it just select the row 62 of the DynamicForm.md file.
> 
> Nevermind, forgot to submit my review.........🤦‍♂️
> 
> Sorry about that.

No problem, I've resolved the change request.

2023-11-27 08:24 UTC, merged