Complete translations for Czech locale (cs-CZ)
pnp/sp-dev-fx-controls-react pull request #1677
Opened 2023-10-12 20:53 UTC by sinkien

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  |  none

#### What's in this Pull Request?

This PR contains a new file cs-cz.ts added to src/loc. This file contains complete translations of strings for Czech locale (cs-CZ).

2024-01-22 09:55 UTC, michaelmaillot requested changes
Please update the `supported.localization.json` file to add the new locale.You can find it [here](https://github.com/pnp/sp-dev-fx-controls-react/blob/dev/config/supported.localization.json#L2).

2024-01-22 09:55 UTC, michaelmaillot commented on src/loc/cs-cz.ts
> +    "customDisplayName": "Použít toto umístění:",
There're missing location props that should be translated:

* `DynamicFormChooseFileLabel`
* `DynamicFormChooseFileButtonText`
* `DynamicFormRequiredFileMessage`

You can find example [here](https://github.com/pnp/sp-dev-fx-controls-react/blob/dev/src/loc/en-us.ts#L391)

2024-01-22 09:55 UTC, michaelmaillot commented on src/loc/cs-cz.ts
> +    "UploadFilesUploadButtonLabel": "Nahrát",
There's a missing location prop regarding a new control added recently :

* `HoverReactionBarSearchEmojiPlaceholder`

You can find it [here](https://github.com/pnp/sp-dev-fx-controls-react/blob/dev/src/loc/en-us.ts#L429)

2024-01-22 09:55 UTC, michaelmaillot commented on src/controls/dynamicForm/DynamicForm.tsx
> +            if (item !== null && item[field.InternalName] !== null && item[field.InternalName].results !== null) {
This update shouldn't be relevant once your branch wull be updated with latest commits on dev

2024-01-22 09:56 UTC, michaelmaillot commented
Hi @sinkien,

Thanks for this PR!

I've submitted a tiny review regarding the translation file. Also, could you update your branch to reflect latest updates made on dev one?

Let me know if something's wrong.

2024-03-29 08:19 UTC, michaelmaillot commented
Hi @sinkien,

Are you still working on this one? Do you need any help?

2024-04-02 19:11 UTC, closed without merging

2024-04-02 19:17 UTC, sinkien commented
Scraping this PR, because everything went haywire. I'll submit new.