Fix #1721
pnp/sp-dev-fx-controls-react pull request #1722
Opened 2023-12-07 14:51 UTC by nsoeth

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [ ]
| New sample?      | [x]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

This PR will fix #1721 

#### Guidance
- *You can delete this section when you are submitting the pull request.* 
- *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
- *Please target your PR to **dev** branch.*

2024-02-08 17:24 UTC, michaelmaillot commented
Hi @nsoeth,

Thanks for this PR!

Regarding the addition of _$top_ query operation, I'd suggest to make it available as optional because it depends on use case and maybe it would not fit for everyone to load 5000 items at once.

Since the DynamicForm lookup field relies on `ListItemPicker` control, and in order to be available as a field override prop for the DynamicForm, here are the different files to update according to me:

* [SPService.ts](https://github.com/pnp/sp-dev-fx-controls-react/blob/285cb32559ccb345e53deb388a3ad1aa9e97af6a/src/services/SPService.ts#L214)
* [IListItemPieckerProps](https://github.com/pnp/sp-dev-fx-controls-react/blob/285cb32559ccb345e53deb388a3ad1aa9e97af6a/src/controls/listItemPicker/IListItemPickerProps.ts#L5)
* [ListItemPicker](https://github.com/pnp/sp-dev-fx-controls-react/blob/285cb32559ccb345e53deb388a3ad1aa9e97af6a/src/controls/listItemPicker/ListItemPicker.tsx#L178) (`ListItemPicker`control doc will have to be updated as there will be a new prop available)
* [IDynamicFieldProps](https://github.com/pnp/sp-dev-fx-controls-react/blob/285cb32559ccb345e53deb388a3ad1aa9e97af6a/src/controls/dynamicForm/dynamicField/IDynamicFieldProps.ts#L8)
* [DynamicField](https://github.com/pnp/sp-dev-fx-controls-react/blob/285cb32559ccb345e53deb388a3ad1aa9e97af6a/src/controls/dynamicForm/dynamicField/DynamicField.tsx#L27)

Like this, the developer will be free to set the number of items he wants to get 🙂 

A suggestion of prop name could be `itemsQueryCountLimit` or `ODataTopCount` for example but feel free to suggest!

Let me know if something's not clear or if you need help.

2024-02-27 13:32 UTC, nsoeth commented
Hi @michaelmaillot ,
Thanks for your suggestions, I updated the PR. 

Kind regards,
Niels

2024-04-12 15:17 UTC, michaelmaillot requested changes
I've submitted a fews changes to be done, let me know if you want any kind of help 🙂

2024-04-12 15:17 UTC, michaelmaillot commented on src/services/SPService.ts
> +              let value = element[fieldName][lookupFieldName || 'Title'];
This should be `element[lookupFieldName || 'Title']` because you've already iterate into the `fieldName` data.

2024-05-29 05:59 UTC, michaelmaillot commented
Hi @nsoeth,

Are you still working on this one? Do you need any kind of help?

2024-05-29 12:26 UTC, nsoeth commented
Hi @michaelmaillot 
Sorry, lot of things to do the last few months but I updated the PR according to your review.

2024-07-31 07:00 UTC, merged

2024-07-31 07:00 UTC, michaelmaillot commented
Merged manually, thank you!