Fixing the bugfix #1718
pnp/sp-dev-fx-controls-react pull request #1736
Opened 2024-01-11 08:10 UTC by IRRDC

Bugfix #1718 for bug #1717 was faulty and gets fixed with this.

| Q               | A
| --------------- | ---
| Bug fix?        | [X]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #1717 

#### What's in this Pull Request?

Removed the wrongly added reference to "results".

2024-01-15 22:43 UTC, michaelmaillot requested changes
Thanks for this PR! I've add a small change request.

2024-01-15 22:43 UTC, michaelmaillot commented on src/controls/dynamicForm/DynamicForm.tsx
> +            } else if (defaultValue) {
Lines 609-616 can also be removed (as default values are handled below), they raised an error when loading a new item with default terms configured on the field.

2024-01-16 06:56 UTC, IRRDC commented
@michaelmaillot Thank you for noticing that. I have updated the code.

2024-01-16 13:00 UTC, michaelmaillot commented
Sorry @IRRDC but as this is a hotfix release, target branch will be dev and not main (then we will cherry-pick your fix to master in order to release a patch verison).

Would you mind resolving conflicts before the merge?

2024-01-16 13:28 UTC, IRRDC commented
@michaelmaillot should be resolved now.

2024-01-16 16:11 UTC, michaelmaillot commented
Sorry @IRRDC but old code is still present [here](https://github.com/pnp/sp-dev-fx-controls-react/pull/1736/commits/0065dab67da94010e7d049de7da528f4c343fdb5#diff-0cf968dc2eb61b72577675d2abf5f042e96e879454818cfa388211bfcb43ecdcR1204)

2024-01-17 05:35 UTC, IRRDC commented
@michaelmaillot Looks like the merge removed all my changes. I have restored them now.

2024-01-17 09:28 UTC, michaelmaillot approved these changes

2024-01-18 08:55 UTC, merged