className and style property added in RichText control
pnp/sp-dev-fx-controls-react pull request #1768
Opened 2024-02-17 10:28 UTC by HarminderSethi

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

className property  assigned to ReactQuill which was missing and also added style property. Both will provide the flexiblity to style the control as per the needs.

2024-02-21 23:19 UTC, joelfmrodrigues commented
Hi @HarminderSethi many thanks for this. While reviewing, I noticed that the className property is already being added to the top-level element of the render method (line 519)
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/19577724/2285ca00-9ad8-4319-a2b3-1201187d41c4)

Please add a new property instead of re-using the existing one as I assume that specifying styles for both components could sometimes become tricky.  Of course, I am happy to be convinced otherwise if you believe one property is the best approach.

2024-02-21 23:22 UTC, joelfmrodrigues requested changes

2024-02-21 23:22 UTC, joelfmrodrigues commented on src/controls/richText/RichText.tsx
> +    const { placeholder,className, styleOptions: { showStyles, showBold, showItalic, showUnderline, showAlign, showList, showLink, showMore, showImage } } = this.props;
Can you please also add props.style here so it follows the same code style?

2024-02-21 23:22 UTC, joelfmrodrigues commented on src/controls/richText/RichText.types.ts
> +  style?: React.CSSProperties
Can you please also add the new property to the docs?

2024-02-21 23:27 UTC, joelfmrodrigues commented
Apologies @HarminderSethi , one more thing: I have updated the PR to target the `dev` branch and there is a conflict that needs to be resolved. Can you please do this by pulling the latest version from the dev branch?
It's a few things but hopefully all quick to resolve. Let us know if you need help with any issues.

2024-02-24 07:08 UTC, closed without merging

2024-02-24 07:36 UTC, HarminderSethi commented
@joelfmrodrigues  Thanks for reviewing and sharing your inputs. I had to delete my fork repository as I created the fork with master branch only. Created new fork and submitted the new pull request.

Also after analysing the changes I found that className property for React Quill control will not make any impact so removed it. and also style property is added to root div similar to className to make consistentency of the implementation.