FileTypeIcon enhancements
pnp/sp-dev-fx-controls-react pull request #1789
Opened 2024-03-10 17:14 UTC by GuidoZam

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | #270 

#### What's in this Pull Request?

Added some events to the FileTypeIcon control.

The new events are the following:
- onClick
- onDoubleClick
- onMouseEnter
- onMouseLeave
- onMouseOver
- onMouseUp

2024-04-25 14:50 UTC, michaelmaillot requested changes
Hi @GuidoZam,

Thanks for submitting this PR!

I have added a few changes to make.

2024-04-25 14:50 UTC, michaelmaillot commented on src/controls/fileTypeIcon/IFileTypeIcon.ts
> +import { FocusEventHandler, KeyboardEventHandler, MouseEventHandler, ReactEventHandler } from "react";
Please remove unused imports

2024-04-25 14:50 UTC, michaelmaillot commented on docs/documentation/docs/controls/FileTypeIcon.md
> +| onMouseEnter | React.MouseEvent\<HTMLElement> | no | Event triggered when the mouse cursor enter the icon. |
```suggestion
| onMouseEnter | React.MouseEvent&lt;HTMLElement&gt; | no | Event triggered when the mouse cursor enters the icon (without event bubbling). |
```

2024-04-25 14:50 UTC, michaelmaillot commented on docs/documentation/docs/controls/FileTypeIcon.md
> +| onMouseLeave | React.MouseEvent\<HTMLElement> | no | Event triggered when the mouse cursor leave the icon. |
```suggestion
| onMouseLeave | React.MouseEvent&lt;HTMLElement&gt; | no | Event triggered when the mouse cursor leaves the icon. |
```

2024-04-25 14:50 UTC, michaelmaillot commented on docs/documentation/docs/controls/FileTypeIcon.md
> +| onMouseOver | React.MouseEvent\<HTMLElement> | no | Event triggered when the mouse cursor is over the icon. |
```suggestion
| onMouseOver | React.MouseEvent&lt;HTMLElement&gt; | no | Event triggered when the mouse cursor enters the icon (with event bubbling). |
```

2024-04-25 14:50 UTC, michaelmaillot commented on docs/documentation/docs/controls/FileTypeIcon.md
> +| onClick | React.MouseEvent\<HTMLElement> | no | Event triggered when the icon is clicked. |
```suggestion
| onClick | React.MouseEvent&lt;HTMLElement&gt; | no | Event triggered when the icon is clicked. |
```

2024-04-25 14:50 UTC, michaelmaillot commented on docs/documentation/docs/controls/FileTypeIcon.md
> +| onDoubleClick | React.MouseEvent\<HTMLElement> | no | Event triggered when the icon is double clicked. |
```suggestion
| onDoubleClick | React.MouseEvent&lt;HTMLElement&gt; | no | Event triggered when the icon is double clicked. |
```

2024-04-25 14:50 UTC, michaelmaillot commented on docs/documentation/docs/controls/FileTypeIcon.md
> +| onMouseUp | React.MouseEvent\<HTMLElement> | no | Event triggered when the mouse button is released after clicked on the icon. |
```suggestion
| onMouseUp | React.MouseEvent&lt;HTMLElement&gt; | no | Event triggered when the mouse button is released after clicked on the icon. |
```

2024-05-01 08:11 UTC, GuidoZam commented
Hi @michaelmaillot, thanks for the reviews. I've made the changes you asked for 👍

2024-05-06 16:36 UTC, merged

2024-05-06 16:36 UTC, michaelmaillot commented
Merged manually, thank you!