Added choice radio button handling
pnp/sp-dev-fx-controls-react pull request #1798
Opened 2024-03-23 18:16 UTC by GuidoZam

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | fixes #1797 

#### What's in this Pull Request?

Added handling of the choice field when set to radio button instead of dropdown.

2024-05-14 23:14 UTC, joelfmrodrigues commented
@GuidoZam many thanks for the improvements. I reviewed it and all seems fine, but I will consider waiting for #1726 to avoid conflicts. If the other PR doesn't move forward quickly, I will then merge this PR first.

2024-05-15 10:50 UTC, GuidoZam commented
Thanks @joelfmrodrigues for the update, I'll wait for the merge 😁

2024-07-02 13:07 UTC, IRRDC commented
I just wrote the same feature and then I found this :-)
Is it going to be included in a release build soon?

2024-07-02 13:15 UTC, GuidoZam commented
@IRRDC I think we're still waiting for the other PR.
@joelfmrodrigues do you have any news?

2024-07-02 15:44 UTC, joelfmrodrigues commented
@GuidoZam hi, sorry I have been struggling to find time and was a bit away from things for personal reasons. Hope to get moving again soon

2024-07-02 16:00 UTC, GuidoZam commented
Hope everything's fine @joelfmrodrigues!
I didn't want to rush you, I was just checking 😉

2024-07-03 06:08 UTC, IRRDC commented
@GuidoZam I tested your code and would suggest that you remove these two lines:
![Zwischenablage04](https://github.com/pnp/sp-dev-fx-controls-react/assets/11270504/d02a12c7-68f7-4fa4-9974-e34080e99a4f)
since they lead to duplicate labels and make the field always required.
Before removing them:
![Zwischenablage013](https://github.com/pnp/sp-dev-fx-controls-react/assets/11270504/ff35c2f3-3fc9-464c-8997-2172eab37d10)
After removing them:
![Zwischenablage02](https://github.com/pnp/sp-dev-fx-controls-react/assets/11270504/77e554fd-053a-44fc-abb3-befcb8cd5ae8)

2024-07-03 07:39 UTC, GuidoZam commented
Thanks for the feedback @IRRDC!!
I've updated the code.

2025-03-04 21:28 UTC, michaelmaillot commented
Hi Guido, would you mind updating your branch / PR regarding conflicts? Thanks.

2025-03-22 22:17 UTC, GuidoZam commented
Hi @michaelmaillot, I've resolved the conflicts.

2025-03-23 17:58 UTC, michaelmaillot requested changes
Thanks for the update!

I think you've missed the `choiceType` variable init during the PR's sync with dev branch [here](https://github.com/pnp/sp-dev-fx-controls-react/pull/1798/files#diff-0cf968dc2eb61b72577675d2abf5f042e96e879454818cfa388211bfcb43ecdcR1170):

```tsx
// Store the choice type for Choice fields
// This represent the format of the choice field (Dropdown or Radio Buttons)
choiceType = field.FormatType;
```

A few things to update and we should be fine.

2025-03-23 17:58 UTC, michaelmaillot commented on src/controls/dynamicForm/dynamicField/DynamicField.tsx
> +        let choiceControl: any = undefined;
```suggestion
        let choiceControl: JSX.Element = undefined;
```

2025-03-23 17:58 UTC, michaelmaillot commented on src/controls/dynamicForm/dynamicField/DynamicField.tsx
```suggestion
}
```

2025-03-23 17:59 UTC, michaelmaillot commented on src/controls/dynamicForm/dynamicField/DynamicField.tsx
>        case 'Choice':
```suggestion
      case 'Choice': {
```

2025-05-03 10:38 UTC, GuidoZam commented
Hi @michaelmaillot, sorry for the late reply!
Thanks for the review, I've updated the PR accordingly, now it should be ready to go 🤞

2025-05-09 16:14 UTC, michaelmaillot requested changes
Thanks for this update, a few changes and we'll be good!

2025-05-18 15:07 UTC, GuidoZam commented
Hi @michaelmaillot I've updated accordingly to your latest suggestions.

2025-05-22 06:33 UTC, merged

2025-05-22 06:33 UTC, michaelmaillot commented
Merged manually, thank you!