Added new WidgetSize
pnp/sp-dev-fx-controls-react pull request #1845
Opened 2024-07-03 13:59 UTC by GuidoZam

| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Added a new WidgetSize to expand the widget width to four places inside the Dashboard control.

2024-08-12 15:25 UTC, michaelmaillot requested changes
Hi @GuidoZam,

Thanks for this improvment! I've added few things to update then we'll be good to go 🙂

2024-08-14 07:10 UTC, GuidoZam commented on src/controls/dashboard/widget/IWidget.ts
> +  Quadruple = "quadruple",
Updated in the next commit.

2024-08-14 07:10 UTC, GuidoZam commented on src/controls/dashboard/widget/Widget.tsx
> +    if (widget.size === WidgetSize.Quadruple) {
Updated in the next commit.

2024-08-14 07:16 UTC, GuidoZam commented
Hi @michaelmaillot, I've resolved your change requests 😊

2024-08-16 07:55 UTC, merged

2024-08-16 07:55 UTC, michaelmaillot commented
Merged manually, thank you!