[Dynamic Form] Fix for 1788/1794 and add styles property for support customizing styling
pnp/sp-dev-fx-controls-react pull request #1913
Opened 2024-11-29 08:29 UTC by wuxiaojun514

| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | fixes #1788 , partially #1794 

#### What's in this Pull Request?

This PR is mainly for 

- Dynamic Form has quite a lot of problems when [custom list formatting](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-configuration) is enabled. I fixed the issues (#1788  ,#1794 Bad UI) .
The author of #1794 provided some other approach to customize the styling but I feel this PR should work.
Now it will show 3 columns per row if it has custom form layout
![image](https://github.com/user-attachments/assets/55591f74-6fb4-4d29-a496-03e20af9f4a7)

-  Added two properties (styles and className) to support customization on styling and converted this component as [style-able component](https://github.com/microsoft/fluentui/blob/master/docs/react-wiki-archive/Component-Styling.md#creating-a-styleable-component).  Deleted the **/dynamicForm/DynamicForm.module.scss** file and put its content into _**/dynamicForm/DynamicForm.sytles.ts**_ and _**/dynamicForm/dynamicField/DynamicField.styles.ts**_ . I kept the same classname on styling to make this change smoothly.  

I have documented the new feature on [DynamicForm.md](https://github.com/wuxiaojun514/sp-dev-fx-controls-react/blob/fix-for-1788-and-add-styles-property/docs/documentation/docs/controls/DynamicForm.md#idynamicformstyles-interface) and given an example how to overwrite styling

I know it is quite a big change, please let me know if anything missing.

#### Guidance
- *You can delete this section when you are submitting the pull request.* 
- *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
- *Please target your PR to **dev** branch.*

2025-01-13 06:26 UTC, wuxiaojun514 commented
Hi @joelfmrodrigues , could you look into it if you have some time?
This PR is for fixing two bugs (#1788 ,#1794 ) on Dynamic Form when list has enabled section layout and introduced **className** and **styles** property on this control so developer can customize the styling on it.
I also updated the related documentation for the new feature.
This PR changed quite a lot of code so it is very easy to have conflict with other submission ( I already fixed the conflicts two times), so I hope it can be reviewed early...
Please contact me if anything unclear or I need modify it.

2025-01-21 21:48 UTC, Marinofull commented
Hi @joaojmendes any updates here?

2025-02-17 10:33 UTC, CodingSinceThe80s commented
Hi all, just wanted to add my feedback: this would be a very useful feature so looking forward to it 👍

2025-02-17 10:36 UTC, joelfmrodrigues commented
@wuxiaojun514 apologies for the delay, I have seen the email notification when you tagged me a while ago but things have been a bit chaotic (in a good way 😇 ) at my end and I have been unable to look into it

2025-02-18 01:50 UTC, wuxiaojun514 commented
Hi @joelfmrodrigues , never mind, just take your time 😄

2025-03-13 09:33 UTC, michaelmaillot requested changes
Hey @wuxiaojun514, this is a great improvment, thanks!

I made some suggestions and one issue when trying to test on my side, please have a look and let me know.

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +| styles | IStyleFunctionOrObject&lt;IDynamicFormStyleProps, [IDynamicFormStyles](#IDynamicFormStyles)&gt; | no | Styles to apply on control.  See the example [here](#how-to-use-styles-property) |
```suggestion
| styles | IStyleFunctionOrObject&lt;IDynamicFormStyleProps, [IDynamicFormStyles](#idynamicformstyles-interface)&gt; | no | Styles to apply on control.  See the example [here](#how-to-use-styles-property) |
```

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
>  | Property                    | Type    | Required | Description                                                                      |
Please add a line break.

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +| Property | Type  | Description |
Please add a line break.

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +
Please remove one line break.

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +| Property | Type  | Description |
Please add a line break.

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +
Please remove one line break.

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +```TypeScript
Please add a line break.

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +Property styles of Dynamic Form gives you a set of properties which you can use to modify styles.
Please add a line break.

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +## How to use styles property
```suggestion
## How to use styles property
```

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +                  "font-size":"18px" //overwrite the error message font size in Dynamic Field
I was not able to make this work. I tried it with a required Lookup field, without success:

![image](https://github.com/user-attachments/assets/7a00cf02-afb5-4f67-87a4-7302e9acd67e)

Did I miss something?

2025-03-13 09:33 UTC, michaelmaillot commented on src/controls/dynamicForm/DynamicForm.sytles.ts
> +import { IStyle } from '@fluentui/react';
I think this file should be named "DynamicForm.**styles**.ts" not "DynamicForm.**sytles**.ts"

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +| sectionTitle | IStyle | styles for the **section title** when your list has enabled [list formatting on form layout](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-
```suggestion
| sectionTitle | IStyle | styles for the **section title** when your list has enabled [list formatting on form layout](https://learn.microsoft.com/sharepoint/dev/declarative-customization/list-form-configuration#configure-custom-body-with-one-or-more-sections) |
```

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +| header | IStyle | styles for the **header** when your list has enabled list formatting on [custom header](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-config
```suggestion
| header | IStyle | styles for the **header** when your list has enabled list formatting on [custom header](https://learn.microsoft.com/sharepoint/dev/declarative-customization/list-form-configuration#configure-custom-header) |
```

2025-03-13 09:33 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +| footer | IStyle | styles for the **footer** when your list has enabled list formatting on [custom footer](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-config
```suggestion
| footer | IStyle | styles for the **footer** when your list has enabled list formatting on [custom footer](https://learn.microsoft.com/sharepoint/dev/declarative-customization/list-form-configuration#configure-custom-footer) |
```

2025-03-14 06:19 UTC, wuxiaojun514 commented on docs/documentation/docs/controls/DynamicForm.md
> +                  "font-size":"18px" //overwrite the error message font size in Dynamic Field
It doesn't work  on my side as well.  Currently `subComponentStyles `is not working.     I will fix it and let you know

2025-03-14 07:53 UTC, wuxiaojun514 commented on docs/documentation/docs/controls/DynamicForm.md
> +                  "font-size":"18px" //overwrite the error message font size in Dynamic Field
@michaelmaillot I have fixed it now.
I also updated the sample in documentation https://github.com/wuxiaojun514/sp-dev-fx-controls-react/blob/fix-for-1788-and-add-styles-property/docs/documentation/docs/controls/DynamicForm.md#how-to-use-styles-property 
to handle normal text field (the error message in normal text field is generated inside the fluent ui [TextField](https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield) control, so we need use `selectors `to overwrite it.

```
          styles={{
            sectionFormField: {
              selectors: {
                ':has(div)': {
                  [`@media (min-width: 1280px)`]: {
                    "min-width": '21%',
                    "max-width": '21%' //force show 4 columns per row in big screen size when enabled list custom formatting
                  }
                },
              },
            },

            subComponentStyles: {
              fieldStyles: {
                errormessage: {
                  "font-size": "18px" //overwrite the error message font size in Dynamic Field for Lookup/Note/Date fields (The error message element is generated directly in Dynamic Field control)
                },
                fieldDisplay: {
                  selectors: {
                    '.ms-TextField-errorMessage': {
                      "font-size": "18px !important" //overwrite the error message font size in Dynamic Field for TextField (error message element is wrapped in Fluent UI TextField control, we cannot modify it directly,we have to use 'selectors' to change it)
                    }
                  }
                }
              }
            }
          }}
```

2025-03-14 08:03 UTC, wuxiaojun514 commented
Hi @michaelmaillot 
Much thanks for your review. 
I appreciate your guide and testing!
Now I have updated the documentation with your advice and I have fixed typo issues in the code.
Please let me know if anything else needs fixing.

2025-03-16 21:31 UTC, michaelmaillot requested changes
I tried again and I confirm it works now!

Just a few updates and we'll be good!

2025-03-16 21:31 UTC, michaelmaillot commented on src/controls/dynamicForm/dynamicField/IDynamicFieldProps.ts
> + FieldEditor:IStyle;
Shouldn't it be written like this?

```suggestion
 fieldEditor:IStyle;
```

2025-03-17 02:01 UTC, wuxiaojun514 commented on src/controls/dynamicForm/dynamicField/IDynamicFieldProps.ts
> + FieldEditor:IStyle;
I have corrected the class name and related document (Actually I copied this name from old _DynamicForm.module.scss_ 
 file...)

2025-03-17 08:36 UTC, wuxiaojun514 commented on docs/documentation/docs/controls/DynamicForm.md
> +```TypeScript
![image](https://github.com/user-attachments/assets/7df3227b-92ab-482c-aee6-76cf53a047d1)
Hi @michaelmaillot ,

I added the line break before the sample code, is it correct?

2025-03-17 09:46 UTC, michaelmaillot commented on docs/documentation/docs/controls/DynamicForm.md
> +```TypeScript
Yes!

2025-03-17 09:49 UTC, merged

2025-03-17 09:49 UTC, michaelmaillot commented
Merged manually.

Thank you!